version: '3.8'

services:
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs

  teamcity-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: teamcity-agent
    depends_on:
      - teamcity-server
    environment:
      - SERVER_URL=http://teamcity-server:8111
    volumes:
      - teamcity_agent_conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    restart: always

volumes:
  teamcity_server_data:
  teamcity_server_logs:
  teamcity_agent_conf:
